#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cssselect
Version  : 1.0.0
Release  : 15
URL      : http://pypi.debian.net/cssselect/cssselect-1.0.0.tar.gz
Source0  : http://pypi.debian.net/cssselect/cssselect-1.0.0.tar.gz
Summary  : cssselect parses CSS3 Selectors and translates them to XPath 1.0
Group    : Development/Tools
License  : BSD-3-Clause
Requires: cssselect-python
BuildRequires : cssselect
BuildRequires : lxml
BuildRequires : nose
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : testrepository
BuildRequires : testresources
BuildRequires : testscenarios
BuildRequires : testtools
BuildRequires : unittest2

%description
===================================
cssselect: CSS Selectors for Python
===================================

%package python
Summary: python components for the cssselect package.
Group: Default

%description python
python components for the cssselect package.


%prep
%setup -q -n cssselect-1.0.0

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
