#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cssselect
Version  : 1.1.0
Release  : 43
URL      : https://files.pythonhosted.org/packages/70/54/37630f6eb2c214cdee2ae56b7287394c8aa2f3bafb8b4eb8c3791aae7a14/cssselect-1.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/70/54/37630f6eb2c214cdee2ae56b7287394c8aa2f3bafb8b4eb8c3791aae7a14/cssselect-1.1.0.tar.gz
Summary  : cssselect parses CSS3 Selectors and translates them to XPath 1.0
Group    : Development/Tools
License  : BSD-3-Clause
Requires: cssselect-license = %{version}-%{release}
Requires: cssselect-python = %{version}-%{release}
Requires: cssselect-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pytest

%description
===================================
cssselect: CSS Selectors for Python
===================================

.. image:: https://img.shields.io/pypi/v/cssselect.svg
   :target: https://pypi.python.org/pypi/cssselect
   :alt: PyPI Version

.. image:: https://img.shields.io/pypi/pyversions/cssselect.svg
   :target: https://pypi.python.org/pypi/cssselect
   :alt: Supported Python Versions

.. image:: https://img.shields.io/travis/scrapy/cssselect/master.svg
   :target: https://travis-ci.org/scrapy/cssselect
   :alt: Build Status

.. image:: https://img.shields.io/codecov/c/github/scrapy/cssselect/master.svg
   :target: https://codecov.io/github/scrapy/cssselect?branch=master
   :alt: Coverage report

*cssselect* parses `CSS3 Selectors`_ and translate them to `XPath 1.0`_
expressions. Such expressions can be used in lxml_ or another XPath engine
to find the matching elements in an XML or HTML document.

This module used to live inside of lxml as ``lxml.cssselect`` before it was
extracted as a stand-alone project.

.. _CSS3 Selectors: https://www.w3.org/TR/css3-selectors/
.. _XPath 1.0: https://www.w3.org/TR/xpath/
.. _lxml: http://lxml.de/


Quick facts:

* Free software: BSD licensed
* Compatible with Python 2.7 and 3.4+
* Latest documentation `on Read the Docs <https://cssselect.readthedocs.io/>`_
* Source, issues and pull requests `on GitHub
  <https://github.com/scrapy/cssselect>`_
* Releases `on PyPI <http://pypi.python.org/pypi/cssselect>`_
* Install with ``pip install cssselect``

%package license
Summary: license components for the cssselect package.
Group: Default

%description license
license components for the cssselect package.


%package python
Summary: python components for the cssselect package.
Group: Default
Requires: cssselect-python3 = %{version}-%{release}

%description python
python components for the cssselect package.


%package python3
Summary: python3 components for the cssselect package.
Group: Default
Requires: python3-core
Provides: pypi(cssselect)

%description python3
python3 components for the cssselect package.


%prep
%setup -q -n cssselect-1.1.0
cd %{_builddir}/cssselect-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582914563
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cssselect
cp %{_builddir}/cssselect-1.1.0/LICENSE %{buildroot}/usr/share/package-licenses/cssselect/b44b1b116e90b52ab7da1109a774acce7b67cd35
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cssselect/b44b1b116e90b52ab7da1109a774acce7b67cd35

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
